version: '3.8'

networks:
    dersureinn:
        driver: ${NETWORKS_DRIVER}

services:
    php:
        build:
            context: ./docker/php
            args:
                - PHP_FPM_VERSION=${PHP_FPM_VERSION}
            dockerfile: Dockerfile
        container_name: ${PROJECT_NAME}_app
        restart: unless-stopped
        expose:
            - '9000'       
        volumes:
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        depends_on:
            - ${PMA_DB_ENGINE}            
        networks:
            - dersureinn
    
    nginx:
        image: nginx:${NGINX_VERSION-alpine}
        container_name: ${PROJECT_NAME}_nginx_server
        restart: unless-stopped
        ports:
            - '${NGINX_HOST_HTTP_PORT}:80'
            - '${NGINX_HOST_HTTPS_PORT}:443'
        volumes:
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
            - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
            - ${NGINX_SITES_PATH}:/etc/nginx/conf.d
            - ${NGINX_SSL_PATH}:/etc/nginx/ssl
        depends_on:
            - php
        networks:
            - dersureinn            

    apache2:
        build:
            context: ./docker/apache2
        container_name: ${PROJECT_NAME}_apache_server
        restart: unless-stopped        
        args:
            - PHP_UPSTREAM_CONTAINER=${APACHE_PHP_UPSTREAM_CONTAINER}
            - PHP_UPSTREAM_PORT=${APACHE_PHP_UPSTREAM_PORT}
            - PHP_UPSTREAM_TIMEOUT=${APACHE_PHP_UPSTREAM_TIMEOUT}
            - DOCUMENT_ROOT=${APACHE_DOCUMENT_ROOT}
            - APACHE_INSTALL_HTTP2=${APACHE_INSTALL_HTTP2}
        volumes:
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
            - ${APACHE_HOST_LOG_PATH}:/var/log/apache2
            - ${APACHE_SITES_PATH}:/etc/apache2/sites-available
            - ${APACHE_SSL_PATH}:/etc/apache2/ssl
        ports:
            - "${APACHE_HOST_HTTP_PORT}:80"
            - "${APACHE_HOST_HTTPS_PORT}:443"
        depends_on:
            - php
        networks:
            - dersureinn

    mysql:
        image: mysql:${MYSQL_VERSION-latest}
        container_name: ${PROJECT_NAME}_db
        restart: unless-stopped
        ports:
            - '${MYSQL_PORT}:3306'            
        environment:
            MYSQL_DATABASE: '${MYSQL_DATABASE}'
            MYSQL_USER: '${MYSQL_USER}'
            MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
            MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - dersureinn
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${MYSQL_ROOT_PASSWORD}"]
            retries: 3
            timeout: 5s
    
    phpmyadmin:
        image: phpmyadmin:${PMA_VERSION-latest}
        container_name: ${PROJECT_NAME}_dbManager
        restart: unless-stopped
        ports:
            - '${PMA_PORT}:80'
        environment:
            PMA_HOST: mysql
        depends_on:
            - ${PMA_DB_ENGINE} 
        networks:
            - dersureinn

    redis:
        image: redis:alpine
        container_name: ${PROJECT_NAME}_cache
        restart: unless-stopped        
        ports:
            - '${REDIS_PORT}:6379'
        volumes:
            - redis:/data
        networks:
            - dersureinn
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
            
    redis-webui:
        build:
            context: ./docker/redis-webui
        environment:
            - ADMIN_USER=${REDIS_WEBUI_USERNAME}
            - ADMIN_PASS=${REDIS_WEBUI_PASSWORD}
            - REDIS_1_HOST=${REDIS_WEBUI_CONNECT_HOST}
            - REDIS_1_PORT=${REDIS_WEBUI_CONNECT_PORT}
            - REDIS_1_AUTH=${REDIS_PASSWORD}
        networks:
            - dersureinn
        ports:
            - "${REDIS_WEBUI_PORT}:80"
        depends_on:
            - redis

volumes:
    dbdata:
        driver: ${VOLUMES_DRIVER}
    redis:
        driver: ${VOLUMES_DRIVER}     
