version: '3.8'

networks:
    dersureinn:
        driver: ${NETWORKS_DRIVER}

services:
    php-fpm:                 
        container_name: ${APP_NAME:-project}_php
        restart: unless-stopped    
        volumes:
            - ${APP_CODE_PATH_HOST?}:${APP_CODE_PATH_CONTAINER?}          
        networks:
            - dersureinn

    php-worker:        
        container_name: ${APP_NAME:-project}_worker
        restart: unless-stopped        
        ports:
            - '9001:9001'      
        volumes:
            - ${APP_CODE_PATH_HOST?}:${APP_CODE_PATH_CONTAINER?}
        networks:
            - dersureinn

    nginx:
        container_name: ${APP_NAME:-project}_nginx_server
        restart: unless-stopped
        ports:
            - '${NGINX_HOST_HTTP_PORT:-80}:80'
            - '${NGINX_HOST_HTTPS_PORT:-443}:443'
        volumes:
            - ${APP_CODE_PATH_HOST?}:${APP_CODE_PATH_CONTAINER?}
        depends_on:
            - php-fpm
        networks:
            - dersureinn

    application:
        image: ${DOCKER_NAMESPACE?}/application-${ENV?}:${TAG?}
        build:
            context: ../
            dockerfile: ./images/php/application/Dockerfile
            args:
                - BASE_IMAGE=${DOCKER_NAMESPACE?}/php-base-${ENV?}:${TAG?}
                - APP_SSH_PASSWORD=${APP_SSH_PASSWORD?}
                - ENV=${ENV?}
        container_name: ${APP_NAME:-project}_application
        cap_add:
            - "SYS_PTRACE"
        security_opt:
            - "seccomp=unconfined"
        volumes:
            - ${APP_CODE_PATH_HOST?}:${APP_CODE_PATH_CONTAINER?}    
        ports:
            - "${APPLICATION_SSH_HOST_PORT:-2222}:22"
        tty: true            
        networks:
            - dersureinn
