version: '3.8'

networks:
    dersureinn:
        driver: ${NETWORKS_DRIVER}

services:
    php-fpm:                 
        container_name: ${APP_NAME:-project}_php
        restart: unless-stopped    
        volumes:
            - ${APP_CODE_PATH_HOST?}:${APP_CODE_PATH_CONTAINER?}          
        networks:
            - dersureinn

    php-worker:        
        container_name: ${APP_NAME:-project}_worker
        restart: unless-stopped      
        volumes:
            - ${APP_CODE_PATH_HOST?}:${APP_CODE_PATH_CONTAINER?}
        networks:
            - dersureinn

    nginx:
        container_name: ${APP_NAME:-project}_nginx_server
        restart: unless-stopped
        ports:
            - '${NGINX_HOST_HTTP_PORT:-80}:80'
            - '${NGINX_HOST_HTTPS_PORT:-443}:443'
        volumes:
            - ${APP_CODE_PATH_HOST?}:${APP_CODE_PATH_CONTAINER?}
        depends_on:
            - php-fpm
        networks:
            - dersureinn
