version: '3.9'
        
services:
    php-roadrunner:                 
        image: marin63/php-roadrunner
        build:
            context: ../
            dockerfile: ./images/php/roadrunner/Dockerfile
            target: production
            args:
                - BASE_IMAGE=dersure/php-base-grpc:latest
