version: '3.9'

networks:
    dersureinn:
        driver: ${NETWORKS_DRIVER}

volumes:
    mysql:
        name: mysql-${ENV?}
        driver: ${VOLUMES_DRIVER}
    redis:
        name: redis-${ENV?}
        driver: ${VOLUMES_DRIVER}

services:
    php-fpm:                 
        container_name: ${APP_NAME:-project}_php
        restart: unless-stopped    
        volumes:
            - ${APP_CODE_PATH_HOST?}:${APP_CODE_PATH_CONTAINER?}          
        networks:
            - dersureinn

    php-worker:        
        container_name: ${APP_NAME:-project}_worker
        restart: unless-stopped
        volumes:
            - ${APP_CODE_PATH_HOST?}:${APP_CODE_PATH_CONTAINER?}
        networks:
            - dersureinn

    nginx:
        container_name: ${APP_NAME:-project}_nginx_server
        restart: unless-stopped
        ports:
            - '${NGINX_HOST_HTTP_PORT:-80}:80'
            - '${NGINX_HOST_HTTPS_PORT:-443}:443'
        volumes:
            - ${APP_CODE_PATH_HOST?}:${APP_CODE_PATH_CONTAINER?}
        depends_on:
            - php-fpm
        networks:
            - dersureinn

    mysql:
        image: mysql:${MYSQL_VERSION?}
        container_name: ${APP_NAME:-project}_db
        restart: unless-stopped
        ports:
            - '${MYSQL_HOST_PORT}:3306'            
        environment:
            MYSQL_DATABASE: '${MYSQL_DATABASE:-application_db}'
            MYSQL_USER: '${MYSQL_USER:-application_user}'
            MYSQL_PASSWORD: '${MYSQL_PASSWORD?}'
            MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD?}'
        volumes:
            - mysql:/var/lib/mysql
        networks:
            - dersureinn
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${MYSQL_ROOT_PASSWORD}"]
            retries: 3
            timeout: 5s
            
    redis:
        image: redis:${REDIS_VERSION?}
        container_name: ${APP_NAME:-project}_cache
        restart: unless-stopped        
        ports:
            - '${REDIS_HOST_PORT}:6379'
        volumes:
            - redis:/data
        networks:
            - dersureinn
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
            