version: '3.8'

networks:
    dersureinn:
        driver: ${NETWORKS_DRIVER}

volumes:
    mysql:
        name: mysql-${ENV?}
        driver: ${VOLUMES_DRIVER}
    redis:
        name: redis-${ENV?}
        driver: ${VOLUMES_DRIVER}

services:
    php-fpm:                 
        container_name: ${PROJECT_NAME:-project}_php
        restart: unless-stopped    
        volumes:
            - ${APP_CODE_PATH_HOST?}:${APP_CODE_PATH_CONTAINER?}          
        networks:
            - dersureinn

    php-worker:        
        container_name: ${PROJECT_NAME:-project}_worker
        restart: unless-stopped        
        ports:
            - '9001:9001'      
        volumes:
            - ${APP_CODE_PATH_HOST?}:${APP_CODE_PATH_CONTAINER?}
        networks:
            - dersureinn

    nginx:
        container_name: ${PROJECT_NAME:-project}_nginx_server
        restart: unless-stopped
        ports:
            - '${NGINX_HOST_HTTP_PORT:-80}:80'
            - '${NGINX_HOST_HTTPS_PORT:-443}:443'
        volumes:
            - ${APP_CODE_PATH_HOST?}:${APP_CODE_PATH_CONTAINER?}
        depends_on:
            - php-fpm
        networks:
            - dersureinn
    
    application:
        image: ${DOCKER_NAMESPACE?}/application-${ENV?}:${TAG?}
        build:
            context: ../
            dockerfile: ./images/php/application/Dockerfile
            args:
                - BASE_IMAGE=${DOCKER_NAMESPACE?}/php-base-${ENV?}:${TAG?}
                - APP_SSH_PASSWORD=${APP_SSH_PASSWORD?}
                - ENV=${ENV?}
        # cap_add and security_opt are required to enable strace
        # @see https://stackoverflow.com/a/46676868
        container_name: ${PROJECT_NAME:-project}_application
        cap_add:
            - "SYS_PTRACE"
        security_opt:
            - "seccomp=unconfined"
        volumes:
            - ${APP_CODE_PATH_HOST?}:${APP_CODE_PATH_CONTAINER?}    
        ports:
            - "${APPLICATION_SSH_HOST_PORT:-2222}:22"
        tty: true            
        networks:
            - dersureinn

    mysql:
        image: mysql:${MYSQL_VERSION?}
        container_name: ${PROJECT_NAME:-project}_db
        restart: unless-stopped
        ports:
            - '${MYSQL_HOST_PORT}:3306'            
        environment:
            MYSQL_DATABASE: '${MYSQL_DATABASE:-application_db}'
            MYSQL_USER: '${MYSQL_USER:-application_user}'
            MYSQL_PASSWORD: '${MYSQL_PASSWORD?}'
            MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD?}'
        volumes:
            - mysql:/var/lib/mysql
        networks:
            - dersureinn
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${MYSQL_ROOT_PASSWORD}"]
            retries: 3
            timeout: 5s
            
    redis:
        image: redis:${REDIS_VERSION?}
        container_name: ${PROJECT_NAME:-project}_cache
        restart: unless-stopped        
        ports:
            - '${REDIS_HOST_PORT}:6379'
        volumes:
            - redis:/data
        networks:
            - dersureinn
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
            