services:
    php-base:
        image: ${DOCKER_NAMESPACE?}/php-base-${ENV?}:${TAG?}
        build:
            context: ../
            dockerfile: ./images/php/base/Dockerfile
            args:
                - ALPINE_VERSION=${ALPINE_VERSION?}
                - PHP_VERSION=${PHP_VERSION?}
                - APP_CODE_PATH=${APP_CODE_PATH_CONTAINER?} 
                - COMPOSER_VERSION=${COMPOSER_VERSION?}
                - ENV=${ENV?}   
                - INSTALL_OPCACHE=${PHP_INSTALL_OPCACHE}    
                - APP_USER_ID=${APP_USER_ID?}            
                - APP_GROUP_ID=${APP_GROUP_ID?}            
                - APP_USER_NAME=${APP_USER_NAME?}            
                - APP_GROUP_NAME=${APP_GROUP_NAME?}
            target: ${ENV?}
        