version: '3.8'

networks:
    dersureinn:
        driver: ${NETWORKS_DRIVER}

volumes:
    dbdata:
        driver: ${VOLUMES_DRIVER}
    redis:
        driver: ${VOLUMES_DRIVER}
        
services:
    php:
        build:
            context: ../images/php/fpm/supervisor
            dockerfile: Dockerfile
            args:
                - PHP_FPM_VERSION=${PHP_FPM_VERSION-fpm-alpine-fpm-alpine}
                - APP_CODE_PATH=${APP_CODE_PATH_CONTAINER}   
                - COMPOSER_VERSION=${COMPOSER_VERSION}            
                - APP_USER_ID=${APP_USER_ID}            
                - APP_GROUP_ID=${APP_GROUP_ID}            
                - APP_USER_NAME=${APP_USER_NAME}            
                - APP_GROUP_NAME=${APP_GROUP_NAME}            
        container_name: ${PROJECT_NAME}_app
        restart: unless-stopped
        expose:
            - '9000'   
        ports:
            - '9001:9001'                
        volumes:
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
            - ../images/php/fpm/conf:/usr/local/etc/php/conf.d          
        networks:
            - dersureinn
    
    nginx:
        image: nginx:${NGINX_VERSION-alpine}
        container_name: ${PROJECT_NAME}_nginx_server
        restart: unless-stopped
        ports:
            - '${NGINX_HOST_HTTP_PORT}:80'
            - '${NGINX_HOST_HTTPS_PORT}:443'
        volumes:
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
            - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
            - ${NGINX_SITES_PATH}:/etc/nginx/conf.d
            - ${NGINX_SSL_PATH}:/etc/nginx/ssl
        depends_on:
            - php
        networks:
            - dersureinn
