version: '3.8'

networks:
    dersureinn:
        driver: ${NETWORKS_DRIVER}

volumes:
    dbdata:
        driver: ${VOLUMES_DRIVER}
    redis:
        driver: ${VOLUMES_DRIVER}

services:
    php-fpm:
        build:
            context: ../images/php/fpm
            dockerfile: Dockerfile
            args:
                - PHP_FPM_VERSION=${PHP_FPM_VERSION-fpm-alpine-fpm-alpine}
                - APP_CODE_PATH=${APP_CODE_PATH_CONTAINER}   
                - COMPOSER_VERSION=${COMPOSER_VERSION}            
                - APP_USER_ID=${APP_USER_ID}            
                - APP_GROUP_ID=${APP_GROUP_ID}            
                - APP_USER_NAME=${APP_USER_NAME}            
                - APP_GROUP_NAME=${APP_GROUP_NAME}                        
        container_name: ${PROJECT_NAME}_app
        restart: unless-stopped
        expose:
            - '9000'       
        volumes:
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
            - ../images/php/fpm/conf:/usr/local/etc/php/conf.d
        depends_on:
            - ${PMA_DB_ENGINE}            
        networks:
            - dersureinn

    php-worker:
        build:
            context: ../images/php/worker
            dockerfile: Dockerfile 
            args:
                - APP_USER_ID=${APP_USER_ID}            
                - APP_GROUP_ID=${APP_GROUP_ID}            
                - APP_USER_NAME=${APP_USER_NAME}            
                - APP_GROUP_NAME=${APP_GROUP_NAME}              
        ports:
            - '9001:9001'         
        networks:
            - dersureinn

    nginx:
        image: nginx:${NGINX_VERSION-alpine}
        container_name: ${PROJECT_NAME}_nginx_server
        restart: unless-stopped
        ports:
            - '${NGINX_HOST_HTTP_PORT}:80'
            - '${NGINX_HOST_HTTPS_PORT}:443'
        volumes:
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
            - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
            - ${NGINX_SITES_PATH}:/etc/nginx/conf.d
            - ${NGINX_SSL_PATH}:/etc/nginx/ssl
        depends_on:
            - php-fpm
        networks:
            - dersureinn            

    apache2:
        image: httpd:${APACHE_VERSION-alpine}
        container_name: ${PROJECT_NAME}_apache_server
        restart: unless-stopped        
        volumes:
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
            - ${APACHE_HOST_LOG_PATH}:/var/log/apache2
            - ${APACHE_SITES_PATH}:/etc/apache2/sites-available
            - ${APACHE_SSL_PATH}:/etc/apache2/ssl
        ports:
            - "${APACHE_HOST_HTTP_PORT}:80"
            - "${APACHE_HOST_HTTPS_PORT}:443"
        depends_on:
            - php-fpm
        networks:
            - dersureinn

    mysql:
        image: mysql:${MYSQL_VERSION-latest}
        container_name: ${PROJECT_NAME}_db
        restart: unless-stopped
        ports:
            - '${MYSQL_HOST_PORT}:3306'            
        environment:
            MYSQL_DATABASE: '${MYSQL_DATABASE}'
            MYSQL_USER: '${MYSQL_USER}'
            MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
            MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - dersureinn
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${MYSQL_ROOT_PASSWORD}"]
            retries: 3
            timeout: 5s
    
    phpmyadmin:
        image: phpmyadmin:${PMA_VERSION-latest}
        container_name: ${PROJECT_NAME}_dbManager
        restart: unless-stopped
        ports:
            - '${PMA_HOST_PORT}:80'
        environment:
            PMA_HOST: mysql
        depends_on:
            - ${PMA_DB_ENGINE} 
        networks:
            - dersureinn
            
    redis:
        image: redis:alpine
        container_name: ${PROJECT_NAME}_cache
        restart: unless-stopped        
        ports:
            - '${REDIS_PORT}:6379'
        volumes:
            - redis:/data
        networks:
            - dersureinn
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s     
