version: '3.8'
        
services:
    php-fpm:
        build:
            context: ../
            dockerfile: ./images/php/fpm/Prod.Dockerfile
            args:
                - APP_CODE_PATH=${APP_CODE_PATH_CONTAINER}       
        expose:
            - '9000'

    php-worker:
        build:
            context: ../
            dockerfile: ./images/php/worker/Dockerfile
            args:
                - APP_USER_ID=${APP_USER_ID}            
                - APP_GROUP_ID=${APP_GROUP_ID}            
                - APP_USER_NAME=${APP_USER_NAME}            
                - APP_GROUP_NAME=${APP_GROUP_NAME}

    nginx:
        build:
            context: ../
            dockerfile: ./images/nginx/Dockerfile
            args:
                - APP_CODE_PATH=${APP_CODE_PATH_CONTAINER}            
                - NGINX_SITES=${NGINX_SITES_PATH}            
        ports:
            - '8080:80'
            - '443:443'
