version: '3.8'

networks:
    dersureinn:
        driver: ${NETWORKS_DRIVER}

services:
    multi-process-app:
        image: ${DOCKER_NAMESPACE?}/multi-process-app
        build:
            context: ../
            dockerfile: ./images/supervisor/Dockerfile
            target: ${ENV?}
            args:
                - BASE_IMAGE=${DOCKER_NAMESPACE?}/php-base-${ENV?}:${TAG?}
                - PHP_WORKER_PROCESS_NUMBER=${PHP_WORKER_PROCESS_NUMBER:-2}         
        container_name: ${PROJECT_NAME}_app
        restart: unless-stopped        
        ports:
            - '9001:9001'    
        volumes:
            - ${APP_CODE_PATH_HOST?}:${APP_CODE_PATH_CONTAINER?}          
        networks:
            - dersureinn       